name: Translate and Build Package

on:
  workflow_dispatch:

  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Translator Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install \
          git \
          gettext \
          npm
          # Install attranslator
          sudo npm install --location=global attranslate

      - name: Translate Package
        shell: bash -O extglob {0}
        env:
          AZURE_KEY: ${{ secrets.AZURE_KEY }}
        run: |
          cd ..
          git clone https://github.com/biglinux/big-auto-translator.git
          mv big-auto-translator/gettext_po_generator_github.sh .
          gitfolder=$(echo ${{ github.repository }} | rev | cut -d "/" -f1 | rev)
          bash gettext_po_generator_github.sh $gitfolder

      - name: Update github
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -n "$(git commit -m "translate $(date +%y-%m-%d_%H:%M)" -a | grep "nothing to commit")" ];then exit 0; fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Send Hooks BigLinux Build Package
        shell: bash
        run: |
          curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package/dispatches
          curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package-ARM/dispatches
          
